platform :ios,’8.0’
use_frameworks!
xcodeproj 'YiNuanTong.xcodeproj'
target 'YiNuanTong' do
pod 'AFNetworking', '~> 3.1.0’
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension'
pod 'SDWebImage', '~> 3.7.2'
pod 'SDCycleScrollView', '~> 1.64'
pod 'Masonry'
pod 'DZNEmptyDataSet'
end